name = "go-proxy-bingai"
main = "worker.js"
compatibility_date = "2024-04-29"
workers_dev = true
rules = [
  { type = "ESModule", globs = ["**/*.js"], fallthrough = true }
]

[placement]
mode = "smart"
[vars]
APIKEY = "sk-erKsBNy!Io3xR5v4lfP4eTbUFXbCnPtXT$gj$3jophlk&&yqLfrrdPgVaUL*^F#0Es^blu0l@EU@Z82A5kgJ&2NEMr5ZBRRNIDIccL%C05zcno%hzDW41pNPN9d#ZB4O"
